import { buildRecipientDetailPageData } from "./recipient-detail-model";

describe("buildRecipientDetailPageData", () => {
  it("sorts identifiers by transaction count descending", () => {
    const pageData = buildRecipientDetailPageData({
      id: 7,
      uuid: "rcp-7",
      displayName: "Sample Recipient",
      normalizedName: "sample recipient",
      createdAt: "2026-06-01T00:00:00.000Z",
      updatedAt: "2026-06-30T00:00:00.000Z",
      transactionCount: 5,
      identifiers: [
        {
          id: 101,
          uuid: "rid-low",
          kind: "UPI_ID",
          value: "low@upi",
          normalizedValue: "low@upi",
        },
        {
          id: 102,
          uuid: "rid-high",
          kind: "CARD_MERCHANT",
          value: "HIGH CARD",
          normalizedValue: "high card",
        },
        {
          id: 103,
          uuid: "rid-mid",
          kind: "TEXT",
          value: "mid text",
          normalizedValue: "mid text",
        },
      ],
      linkedTransactions: [
        {
          id: 1,
          uuid: "txn-1",
          amount: 100,
          currency: "INR",
          type: "UPI",
          source: "sms",
          recipientRaw: "HIGH CARD",
          recipientName: null,
          timestamp: "2026-06-30T10:00:00.000Z",
          category: null,
          subcategory: null,
          categoryId: null,
          subcategoryId: null,
        },
        {
          id: 2,
          uuid: "txn-2",
          amount: 120,
          currency: "INR",
          type: "UPI",
          source: "sms",
          recipientRaw: "HIGH CARD",
          recipientName: null,
          timestamp: "2026-06-29T10:00:00.000Z",
          category: null,
          subcategory: null,
          categoryId: null,
          subcategoryId: null,
        },
        {
          id: 3,
          uuid: "txn-3",
          amount: 80,
          currency: "INR",
          type: "UPI",
          source: "sms",
          recipientRaw: "mid text",
          recipientName: null,
          timestamp: "2026-06-28T10:00:00.000Z",
          category: null,
          subcategory: null,
          categoryId: null,
          subcategoryId: null,
        },
        {
          id: 4,
          uuid: "txn-4",
          amount: 75,
          currency: "INR",
          type: "UPI",
          source: "sms",
          recipientRaw: "low@upi",
          recipientName: null,
          timestamp: "2026-06-27T10:00:00.000Z",
          category: null,
          subcategory: null,
          categoryId: null,
          subcategoryId: null,
        },
        {
          id: 5,
          uuid: "txn-5",
          amount: 90,
          currency: "INR",
          type: "UPI",
          source: "sms",
          recipientRaw: "HIGH CARD",
          recipientName: "mid text",
          timestamp: "2026-06-26T10:00:00.000Z",
          category: null,
          subcategory: null,
          categoryId: null,
          subcategoryId: null,
        },
      ],
    });

    expect(pageData.identifiers.map((identifier) => identifier.id)).toEqual([
      "rid-high",
      "rid-mid",
      "rid-low",
    ]);
    expect(pageData.identifiers.map((identifier) => identifier.transactionCount)).toEqual([
      3,
      2,
      1,
    ]);
  });
});
